DROP TABLE IF EXISTS page;
DROP TABLE IF EXISTS all_pages;

CREATE TABLE page (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  page_id TEXT UNIQUE NOT NULL
);

CREATE TABLE all_pages (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  page_id TEXT UNIQUE NOT NULL,
  properties TEXT NOT NULL,
  summary TEXT NOT NULL,
  tags TEXT NOT NULL,
  title TEXT NOT NULL,
  url TEXT NOT NULL,
  FOREIGN KEY (page_id) REFERENCES page (page_id)
);
